# Generated by Django 5.0.3 on 2024-03-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('cod', models.IntegerField()),
                ('estoque', models.IntegerField()),
                ('bar_cod', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('preco_compra', models.FloatField()),
                ('produto', models.TextField()),
                ('ref', models.TextField()),
                ('marca', models.TextField()),
                ('categoria', models.TextField()),
                ('local', models.TextField()),
                ('fornecedor', models.TextField()),
                ('entrada', models.DateField()),
                ('validade', models.DateField()),
            ],
        ),
    ]
