# Generated by Django 5.0.3 on 2024-03-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
